//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrookedPortal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrookedPortal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eoim2ac05z7x8dfeeznr1pb0.
        /// </summary>
        internal static string EtsyAPIKey {
            get {
                return ResourceManager.GetString("EtsyAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.etsy.com/v3/application/shops/7317374/listings/.
        /// </summary>
        internal static string EtsyListingImagesURL {
            get {
                return ResourceManager.GetString("EtsyListingImagesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.etsy.com/v3/application/listings/.
        /// </summary>
        internal static string EtsyListingProductsURL {
            get {
                return ResourceManager.GetString("EtsyListingProductsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.etsy.com/v3/application/shops/7317374/listings?limit=100.
        /// </summary>
        internal static string EtsyListingsURL {
            get {
                return ResourceManager.GetString("EtsyListingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7317374.
        /// </summary>
        internal static string EtsyShopID {
            get {
                return ResourceManager.GetString("EtsyShopID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.etsy.com/v3/public/oauth/token.
        /// </summary>
        internal static string EtsyTokenDataURL {
            get {
                return ResourceManager.GetString("EtsyTokenDataURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ce92f37da5c79b11715da8705e1b81bf.
        /// </summary>
        internal static string GCAPIKey {
            get {
                return ResourceManager.GetString("GCAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://getcrooked.myshopify.com/admin/api/2021-10/.
        /// </summary>
        internal static string GCAPIURL {
            get {
                return ResourceManager.GetString("GCAPIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34454569002.
        /// </summary>
        internal static string GCLocationID {
            get {
                return ResourceManager.GetString("GCLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 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.
        /// </summary>
        internal static string GCPassword {
            get {
                return ResourceManager.GetString("GCPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e8bc8eab3d3c64830e82f3fad0526f73.
        /// </summary>
        internal static string MCTAPIKey {
            get {
                return ResourceManager.GetString("MCTAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://crooked-knitwear.myshopify.com/admin/api/2021-10/.
        /// </summary>
        internal static string MCTAPIURL {
            get {
                return ResourceManager.GetString("MCTAPIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35626156122.
        /// </summary>
        internal static string MCTLocationID {
            get {
                return ResourceManager.GetString("MCTLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 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.
        /// </summary>
        internal static string MCTPassword {
            get {
                return ResourceManager.GetString("MCTPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string ShopifyProductsURL {
            get {
                return ResourceManager.GetString("ShopifyProductsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json?limit=250&amp;amp;published_status=any&amp;amp;fields=id%2Ctitle%2Cbody_html%2Cimages%2Ctags%2Cvariants%2Ccreated_at%2Cstatus%2Cpublished_at%2Cpublished_scope.
        /// </summary>
        internal static string ShopifyProductsURLFields {
            get {
                return ResourceManager.GetString("ShopifyProductsURLFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source= mssqluk20.prosql.net;Initial Catalog=crookedportal;User Id=cragga;Password=cr@Ggl3r0ck;.
        /// </summary>
        internal static string SQLServerConnectionString {
            get {
                return ResourceManager.GetString("SQLServerConnectionString", resourceCulture);
            }
        }
    }
}
