//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrookedPortal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25090048.17uZp-Ua-J3h57vDTEJCQU5mc_R9tfoq6WabStEtv3WpV2rN8yEg35qhD583FHLN6ifDAbbe" +
            "HkFhZuRGGStIG21QVJ7!")]
        public string EtsyAPIRefreshToken {
            get {
                return ((string)(this["EtsyAPIRefreshToken"]));
            }
            set {
                this["EtsyAPIRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25090048.0SGW8aZMApt0T72UWrzOW5c_kC9WbjrirvIT7y9EHuKtGB5EsFEL9mfkUWIzZLf11bQTdx9o" +
            "n7iyCIBOEpyfkyh0rXV")]
        public string EtsyAPIAccessToken {
            get {
                return ((string)(this["EtsyAPIAccessToken"]));
            }
            set {
                this["EtsyAPIAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index {
            get {
                return ((int)(this["Index"]));
            }
            set {
                this["Index"] = value;
            }
        }
    }
}
